#!/usr/bin/env bash
#Task 4 404 error
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Ceci n'\''est pas un page\n" > /var/www/html/custom_404.html'
myString="\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _;/a $myString" /etc/nginx/sites-available/default
sudo service nginx start
