#!/usr/bin/env bash
#Task 4 404 error
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Ceci n'\''est pas un page" > /var/www/html/404.html'
myString="\n\tlocation = erro_page 404 /404.html {\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _;/a $myString" /etc/nginx/sites-available/default
sudo service nginx start
