#!/usr/bin/env bash
# Install required packages (if not already installed)

apt-get update
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx default site configuration to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# start Nginx to apply changes
chmod 644 /etc/nginx/nginx.conf

pkill apache2

# start Nginx to apply changes
sudo -u nginx service nginx start
